apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturlsvc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorturlsvc
  template:
    metadata:
      labels:
        app: shorturlsvc
    spec:
      containers:
        - name: shorturlsvc
          image: justscroll/shorturlsvc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_DEBUG
              value: "false"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: shorturlsvc-service
  namespace: default
spec:
  selector:
    app: shorturlsvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
